source "azure-arm" "autogenerated_1" {
  azure_tags = {
    env  = "dev"
    task = "Image deployment"
  }
  client_id                         = "d1a040b6-65a4-4916-a85c-bc4e06f14c8f"
  client_secret                     = "5pe8Q~b9FjTVq4hEHMtYqWTiz6AOUPwQFWd3ham_"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "16.04-LTS"
  location                          = "West Europe"
  managed_image_name                = "auberginePackerImage"
  managed_image_resource_group_name = "packerRG"
  os_type                           = "Linux"
  subscription_id                   = "2ec254d2-83e6-416b-969c-7da8030dc771"
  tenant_id                         = "20e2bf23-d13a-42ba-99a4-5bb9fffb68f2"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "{{ .Vars }} sudo -E bash '{{ .Path }}'"
    scripts = [
      "scripts/supportPackages.sh",
      "scripts/kubectl.sh",
      "scripts/python.sh",
      "scripts/helm.sh",
      "scripts/istio.sh",
      "scripts/k9s.sh",
      "scripts/helmdiff.sh",
      "scripts/helmfile.sh",
      "scripts/docker.sh",
      "scripts/cleanup.sh" 
    ]
  }
}