node (label: 'stuff') {   
   stage('Clone repository') {
        checkout scm
    }
    try {
        stage('Setup stuff') {
            // Pull latest container
            sh label: "Setup stuff"
                script: "ls"
        }
        stage('Deploy environment - todo') {
        }
    }
    catch (exc) {
        currentBuild.result = 'FAILURE'
    }
    finally {
        stage('Terraform destroy') {
    }
}